islandora_datacite_doi.settings:
  type: mapping
  label: Settings
  mapping:
    saxon_path:
      type: string
    use_ssl:
      type: string
    prefix:
      type: string
    site:
      type: string
    username:
      type: string
    password:
      type: string
